<form id="registerform" name="registerform" method="post" action="registerform">
  <p>用户名
    <input name="UserName" type="text"  id="UserName" />
  </p>
  <p> 密码
    <input type="password" name="Password" id="Password" />
  </p>
  <p> 密码确认
    <input type="password" name="confirmPassword" id="confirmPassword" />
  </p>
  <p>角色
    <input type="radio" name="UserType" id="UserType" value="<?php echo $this->UserType["Customer"] ?>" />
    Customer<br>
    <input type="radio" name="UserType" id="UserType" value="<?php echo $this->UserType["Admin"] ?>" />
    Admin<br>
  </p>
  <p>
    <input type="submit" name="register" id="register" value="注册" />
  </p>
</form>
