<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="product" content="Metro UI CSS Framework">
<meta name="description" content="Simple responsive css framework">
<meta name="author" content="Sergey S. Pimenov, Ukraine, Kiev">
<!-- Load CSS Libraries -->
<link href="<?php echo $this->baseUrl('/css/metro-bootstrap.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/metro-bootstrap-responsive.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/iconFont.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/docs.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/js/prettify/prettify.css');?>" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Coda' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Jura:400,500,600,300' rel='stylesheet' type='text/css' />

<!-- Load JavaScript Libraries -->
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.widget.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.mousewheel.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/prettify/prettify.js');?>"></script>

<!-- Metro UI CSS JavaScript plugins -->
<script src="<?php echo $this->baseUrl('/js/metro.min.js');?>"></script>
<!-- Local JavaScript -->
<script src="<?php echo $this->baseUrl('/js/docs.js');?>"></script>
<title>Metro UI CSS : Metro Bootstrap CSS Library</title>
</head>
<body class="metro">
<header class="bg-black" data-load="/template/header"></header>
<div class="container">
				<section class="content">
                        <h2>漂流瓶•双城寄</h2>
                        <p>我们是一群热情洋溢的港漂毕业生，我们的目标是为港漂解决最常见最棘手的问题，<font color="purple">我们希望我们的存在能让大家的生活更加便利</font>。漂流瓶•双城寄 是我们推出的第一个项目，也是我们目前主推的一个项目。</p>
                        <br/>
                        <p>漂流瓶•双城寄 中的漂流瓶起源于<font color="purple">港漂、物流</font>两点，我们致力于<font color="purple">做成未来最大覆盖面最广的深港大学物流</font>。我们和腾讯或者其他公司旗下的漂流瓶业务没有任何直接相关关系。</p>
                        <br/>
                        <p>我们这项服务的定位是<font color="purple">在港学生和内地来港工作人员</font>，采取的主要形式是<font color="purple">定点定时派送</font>。我们希望通过我们的平台，能够让大家继续享受到大陆网购的乐趣，而又克服快递的不便利。</p>
						<br/>
                        <p><font color="purple">自从我们服务开展以来，受到了社会方方面面的帮助。不少朋友特地联系我们表示鼓励，一些同学为我们提了很多宝贵的意见，还有许多客户一直信赖我们支持我们，我们在此一并表示感谢。我们会努力改善提高自己，更好地为港漂服务。</font></p>
				</section>
                <section class="content">
                <a name="#52" id="#52"></a>
					<h2>如何联络我们？</h2>
                        <p>非常感谢您对 漂流瓶•双城寄 转运服务（<a href="http://www.PiaoLiuHK.com">http://www.PiaoLiuHK.com</a>）的关注，如果您有什么疑问，或者有任何意见或建议，请联系我们。谢谢。</p>
                        <br/>
                        <br/>
                        <p><strong>官方微博: </strong></p>
					<div class="sinaweibo-wrapper"><div id="sinaweibo" class="sinaweibo"><iframe width="100%" height="300" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=zh_cn&width=0&height=300&fansRow=1&ptype=1&speed=0&skin=9&isTitle=0&noborder=0&isWeibo=1&isFans=1&uid=3821217802&verifier=bf078663&dpc=1"></iframe></div>　</div>　
<br/>
                        <p><strong>官方微信 </strong></p>
                        <p>即将推出，敬请期待</p> 
                        <br/>
				</section>

		
</div>
</body>
</html>