<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="product" content="Metro UI CSS Framework">
<meta name="description" content="Simple responsive css framework">
<meta name="author" content="Sergey S. Pimenov, Ukraine, Kiev">
<!-- Load CSS Libraries -->
<link href="<?php echo $this->baseUrl('/css/metro-bootstrap.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/metro-bootstrap-responsive.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/iconFont.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/docs.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/js/prettify/prettify.css');?>" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Coda' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Jura:400,500,600,300' rel='stylesheet' type='text/css' />

<!-- Load JavaScript Libraries -->
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.widget.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.mousewheel.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/prettify/prettify.js');?>"></script>

<!-- Metro UI CSS JavaScript plugins -->
<script src="<?php echo $this->baseUrl('/js/metro.min.js');?>"></script>
<!-- Local JavaScript -->
<script src="<?php echo $this->baseUrl('/js/docs.js');?>"></script>
<title>Metro UI CSS : Metro Bootstrap CSS Library</title>
</head>
<body class="metro">
<header class="bg-black" data-load="/template/header"></header>
<div class="container">
  	<section class="content">
					<a name="#11" id="#11"></a>
                    <h2>深圳->香港 转运流程介绍</h2>
						<p>1）您在大陆购物网站下单，收货信息请填写我们为您提供的信息。<font color="red"><strong>您亦可登录后在我的“我的收货地址”查看</strong></font>。</p> 
                                                <p>　　　　　　　　　　收货信息：</p>
						<p>　　　　　　　　　　收件人：　您的姓名</p>
                                                <p>　　　　　　　　　　邮政编码：518173</p>
						<p>　　　　　　　　　　收件电话：15818786460</p>
						<p>　　　　　　　　　　收件地址：深圳市龙岗区横岗街道振业城综合大楼176号商铺漂流瓶+您的香港手机号码</p>

						<p>2）请您<font color="red"><strong>务必</strong></font>在网站上登录<font color="red"><strong>通知我们您的包裹数目和相应运单号码</strong></font>，我们会及时追踪和更新包裹。（对于因为未登记造成的派送延迟我们概不负责）</p>
						<p>3） 当全部包裹到达我们香港仓库的时候，我们会根据您的指令将包裹送往香港各大学校分点。</p> 
                        <p>4） 在包裹到达相应分点之后，我们会及时通知您收件。</p>
                        <p>5） 收件,付款。</p>
                        <br/>
                        <p>注： 我们的派送模式是周一到周五<font color="red"><strong>每天固定时间段</strong></font>派送到<font color="red"><strong>各所学校的特定地点</strong></font>（<a href="address.html#21">各所学校派送地点和派送时间请参考这里</a>）。你也可以选择亲临我们香港九龙塘仓库自提（<a href="address.html#25">仓库地址和时间请参考这里</a>）。您亦可以选择让我们派送到您指定的其他地点（<font color="red"><strong>费用不同，不推荐</strong></font>）。</p>
                        <br/>
                        <p><a href="procedure.html#12">运送时效请参考这里</a></p>
                        <br/>
                        <p><a href="fee.html#31">运费请参考这里</a></p>
                        <br/>
                        <p><a href="procedure.html#14">常见问题请参考这里</a></p>
				</section>
</div>
</body>
</html>