<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="product" content="Metro UI CSS Framework">
<meta name="description" content="Simple responsive css framework">
<meta name="author" content="Sergey S. Pimenov, Ukraine, Kiev">
<!-- Load CSS Libraries -->
<link href="<?php echo $this->baseUrl('/css/metro-bootstrap.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/metro-bootstrap-responsive.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/iconFont.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/docs.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/js/prettify/prettify.css');?>" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Coda' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Jura:400,500,600,300' rel='stylesheet' type='text/css' />

<!-- Load JavaScript Libraries -->
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.widget.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.mousewheel.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/prettify/prettify.js');?>"></script>

<!-- Metro UI CSS JavaScript plugins -->
<script src="<?php echo $this->baseUrl('/js/metro.min.js');?>"></script>
<!-- Local JavaScript -->
<script src="<?php echo $this->baseUrl('/js/docs.js');?>"></script>
<title>Metro UI CSS : Metro Bootstrap CSS Library</title>
</head>
<body class="metro">
<header class="bg-black" data-load="/template/header"></header>
<div class="container">
   <section class="content">
					<a name="#13" id="#13"></a>
                    <h2>禁运品清单</h2>
                        <p>1）各类武器、弹药。如枪支、子弹、炮弹、手榴弹、地雷、炸弹等。</p>
                        
                        <p>2）各类易爆炸性物品。如雷管、炸药、火药、鞭炮等。</p>
                        
                        <p>3）各类易燃烧性物品，包括液体、气体和固体。如汽油、煤油、桐油、酒精、生漆、柴油、气雾剂、气体打火机、瓦斯气瓶、磷、硫磺、火柴等。</p>
                        
                        <p>4）各类易腐蚀性物品。如火硫酸、盐酸、硝酸、有机溶剂、农药、双氧水、危险化学品等。</p>
                        
                        <p>5）各类放射性元素及容器。如铀、钴、镭、钚等。</p>
                        
                        <p>6）各类烈性毒药。如铊、氰化物、砒霜等。</p>
                        
                        <p>7）各类麻醉药物。如鸦片（包括罂粟壳、花、苞、叶）、吗啡、可卡因、海洛因、大麻、冰毒、麻黄素及其它制品等。</p>
                        
                        <p>8）各类生化制品和传染性物品。如炭疽、危险性病菌、医药用废弃物等。</p>
                        
                        <p>9）各种危害国家安全和社会政治稳定以及淫秽的出版物、宣传品、印刷品等。</p>
                        
                        <p>10）各种妨害公共卫生的物品。如尸骨、动物器官、肢体、未经硝制的兽皮、未经药制的兽骨等。</p>
                        
                        <p>11）国家法律、法规、行政规章明令禁止流通、寄递或进出境的物品，如国家秘密文件和资料、国家货币及伪造的货币和有价证券、仿真武器、管制刀具、珍贵文物、濒危野生动物及其制品等。</p>
                        
                        <p>12）包装不妥，可能危害人身安全、污染或者损毁其他寄递件、设备的物品等。</p>
                        
                        <p>13）各寄达国（地区）禁止寄递进口的物品等。</p>
                        
                        <p>14）合同，支票等具有商业价值的文件，护照等一切不具备商业价值的文件。（文件运输属于商业快件范畴，我们只能承接个人物品快件）</p>
                        
                        <p>15）西洋参等各种参类形状的保健品禁止运输。</p>
                        
                        <p>16）贵金属，艺术品真迹，海内外古董（真迹）等一切超出快递经营许可的产品。</p>    
				</section>
</div>
</body>
</html>