<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="product" content="Metro UI CSS Framework">
<meta name="description" content="Simple responsive css framework">
<meta name="author" content="Sergey S. Pimenov, Ukraine, Kiev">
<!-- Load CSS Libraries -->
<link href="<?php echo $this->baseUrl('/css/metro-bootstrap.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/metro-bootstrap-responsive.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/iconFont.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/docs.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/js/prettify/prettify.css');?>" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Coda' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Jura:400,500,600,300' rel='stylesheet' type='text/css' />

<!-- Load JavaScript Libraries -->
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.widget.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.mousewheel.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/prettify/prettify.js');?>"></script>

<!-- Metro UI CSS JavaScript plugins -->
<script src="<?php echo $this->baseUrl('/js/metro.min.js');?>"></script>
<!-- Local JavaScript -->
<script src="<?php echo $this->baseUrl('/js/docs.js');?>"></script>
<title>Metro UI CSS : Metro Bootstrap CSS Library</title>
</head>
<body class="metro">
<header class="bg-black" data-load="/template/header"></header>
<div class="container">
  <h2>收取包裹时间和地点</h2>
  <p>注：以下时间仅作参考，每天会有小幅变化，具体以当天短信或电话通知为准。</p>
 
  <section class="content"> <a name="" id=""></a>
    <h2>新界沙田第一城居住区<strong>（提供上门送货服务）</strong></h2>
    <p>时间：11.00pm到11.59pm，每周一至周五，节假日休息</p>
  </section>
  <section class="content"> <a name="" id=""></a>
    <h2>九龙九龙城居住区</h2>
    <p>时间：11.00pm到11.59pm，每周一至周五，节假日休息</p>
    <p><strong>地址：九龙城打鼓岭道23号百营中心黄珍珍餐馆门口</strong></p>
    <div class="map">
      <iframe width="730" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://ditu.google.cn/maps?source=s_q&amp;hl=zh-CN&amp;q=%E7%99%BE%E8%90%A5%E4%B8%AD%E5%BF%83%E9%BB%84%E7%8F%8D%E7%8F%8D%E9%A4%90%E9%A6%86&amp;sll=35.86166,104.195397&amp;sspn=37.453094,75.673828&amp;brcurrent=3,0x31508e64e5c642c1:0x951daa7c349f366f,0%3B5,0,0&amp;ie=UTF8&amp;hq=%E7%99%BE%E8%90%A5%E4%B8%AD%E5%BF%83%E9%BB%84%E7%8F%8D%E7%8F%8D%E9%A4%90%E9%A6%86&amp;hnear=%E9%A6%99%E6%B8%AF%E6%89%93%E9%BC%93%E5%B6%BA%E9%81%9323%E8%99%9F&amp;geocode=FSy2VAEd5GvOBg&amp;ll=22.328926,114.191414&amp;spn=0.042157,0.0739&amp;t=m&amp;z=14&amp;iwloc=A&amp;cid=13168696012247649249&amp;output=embed"></iframe>
    </div>
  </section>
  <section class="content"> <a name="#21" id="#21"></a>
    <h2>香港中文大学</h2>
    <p>时间：6.00pm到6.30pm，每周一至周五，节假日休息</p>
    <p><strong>地址：香港地铁东铁线大学地铁站A出口</strong></p>
    <div class="map">
      <iframe width="730" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://ditu.google.cn/maps?f=d&amp;source=s_d&amp;saddr=22.413729,114.209961&amp;daddr=&amp;hl=zh-CN&amp;geocode=&amp;sll=22.413734,114.209951&amp;sspn=0.001438,0.002642&amp;brcurrent=3,0x31508e64e5c642c1:0x951daa7c349f366f,0%3B5,0,0&amp;mra=mift&amp;mrsp=0&amp;sz=19&amp;ie=UTF8&amp;t=m&amp;ll=22.413734,114.209951&amp;spn=0.001438,0.002642&amp;output=embed"></iframe>
    </div>
  </section>
  <section class="content"> <a name="#22" id="#22"></a>
    <h2>香港城市大学</h2>
    <p>时间：6.30pm到7.00pm，每周一至周五，节假日休息</p>
    <p><strong>地址：香港九龙塘达之路83号香港城市大学图书馆门口</strong></p>
    <div class="map">
      <iframe width="730" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://ditu.google.cn/maps?f=d&amp;source=s_d&amp;saddr=22.33597,114.173574&amp;daddr=&amp;hl=zh-CN&amp;geocode=&amp;sll=22.335751,114.173591&amp;sspn=0.002878,0.005284&amp;brcurrent=3,0x31508e64e5c642c1:0x951daa7c349f366f,0%3B5,0,0&amp;mra=mift&amp;mrsp=0&amp;sz=18&amp;ie=UTF8&amp;t=m&amp;ll=22.335751,114.173591&amp;spn=0.002878,0.005284&amp;output=embed"></iframe>
    </div>
  </section>
  <section class="content"> <a name="#23" id="#23"></a>
    <h2>香港浸会大学</h2>
    <p>时间：6.00pm到7.00pm，每周一至周五，节假日休息</p>
    <p><strong>地址：香港九龙塘地铁站A2出口</strong></p>
    <div class="map">
      <iframe width="730" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://ditu.google.cn/maps?f=d&amp;source=s_d&amp;saddr=22.336898,114.17815&amp;daddr=&amp;hl=zh-CN&amp;geocode=&amp;sll=22.336908,114.178146&amp;sspn=0.002878,0.005284&amp;brcurrent=3,0x31508e64e5c642c1:0x951daa7c349f366f,0%3B5,0,0&amp;mra=mift&amp;mrsp=0&amp;sz=18&amp;ie=UTF8&amp;t=m&amp;ll=22.336908,114.178146&amp;spn=0.002878,0.005284&amp;output=embed"></iframe>
    </div>
  </section>
  <section class="content"> <a name="#24" id="#24"></a>
    <h2>香港理工大学</h2>
    <p>时间：6.30pm到7.00pm，每周一至周五，节假日休息</p>
    <p><strong>地址：香港紅磡地铁站A1出口</strong></p>
    <div class="map">
      <iframe width="730" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://ditu.google.cn/maps?f=d&amp;source=s_d&amp;saddr=22.30346,114.181132&amp;daddr=&amp;hl=zh-CN&amp;geocode=&amp;sll=22.303262,114.181488&amp;sspn=0.005757,0.010568&amp;brcurrent=3,0x31508e64e5c642c1:0x951daa7c349f366f,0%3B5,0,0&amp;mra=mift&amp;mrsp=0&amp;sz=17&amp;ie=UTF8&amp;t=m&amp;ll=22.303262,114.181488&amp;spn=0.005757,0.010568&amp;output=embed"></iframe>
    </div>
  </section>
</div>
</body>
</html>