<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="product" content="Metro UI CSS Framework">
<meta name="description" content="Simple responsive css framework">
<meta name="author" content="Sergey S. Pimenov, Ukraine, Kiev">
<!-- Load CSS Libraries -->
<link href="<?php echo $this->baseUrl('/css/metro-bootstrap.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/metro-bootstrap-responsive.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/iconFont.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/docs.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/js/prettify/prettify.css');?>" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Coda' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Jura:400,500,600,300' rel='stylesheet' type='text/css' />

<!-- Load JavaScript Libraries -->
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.widget.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.mousewheel.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/prettify/prettify.js');?>"></script>

<!-- Metro UI CSS JavaScript plugins -->
<script src="<?php echo $this->baseUrl('/js/metro.min.js');?>"></script>
<!-- Local JavaScript -->
<script src="<?php echo $this->baseUrl('/js/docs.js');?>"></script>
<title>Metro UI CSS : Metro Bootstrap CSS Library</title>
</head>
<body class="metro">
<header class="bg-black" data-load="/template/header"></header>
<div class="container">
  	 <section class="content">
                    <a name="#14" id="#14"></a> 
                    <h3>FAQ</h3>
                        <p><strong>既然收件信息内已包含我的名字和电话作为辨认，为何还要通知你们运单号码？</strong></p>
                        <br/>
                        <p>对于非机打的普通快递，包裹上的快递单信息往往模糊不清，所以我们需要运单号码作为客户凭证。</p>
                        <br/>
                        <p><strong>虽然我有几个包裹，但是我希望每到一个就发到香港一个而不是等到齐了再一起运过来。</strong></p>
                        <br/>
                        <p>你可以选择单独发货，我们以您的指令为准。但是每次发货都将作为一次服务计算收费</p>
                        <br/>
                        <p><strong>香港大学等院校为什么没开通？</strong></p>
                        <br/>
                        <p>试运营期间，我们按照地域远近暂时选取了中文城市理工浸会四所院校以及九龙城和沙田第一城居住区开始我们的业务。我们会在后续陆续开通其他高校，人流密集的地铁站以及高票集中的居住区，敬请关注。目前其他高校的同学亦可以选择就近已开通的地点取货，谢谢。</p>
                                                <br/>
                        <p><strong>收货的收货时间和具体位置好像不是很方便？</strong></p>
                        <br/>
                        <p>我们选取的各校园和居住区是参考了部分同学的意见和建议，但是疏忽和不合理亦在所难免。我们非常欢迎大家对我们的服务提出意见，我们会努力做得更好。谢谢</p>
				</section>
</div>
</body>
</html>