<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="product" content="Metro UI CSS Framework">
<meta name="description" content="Simple responsive css framework">
<meta name="author" content="Sergey S. Pimenov, Ukraine, Kiev">
<!-- Load CSS Libraries -->
<link href="<?php echo $this->baseUrl('/css/metro-bootstrap.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/metro-bootstrap-responsive.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/iconFont.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/css/docs.css');?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('/js/prettify/prettify.css');?>" rel="stylesheet">

<!-- Load JavaScript Libraries -->
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.widget.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/jquery/jquery.mousewheel.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/prettify/prettify.js');?>"></script>

<!-- Metro UI CSS JavaScript plugins -->
<script src="<?php echo $this->baseUrl('/js/metro.min.js');?>"></script>
<!-- Local JavaScript -->
<script src="<?php echo $this->baseUrl('/js/docs.js');?>"></script>
<script src="<?php echo $this->baseUrl('/js/start-screen.js');?>"></script>
<title>Metro UI CSS : Metro Bootstrap CSS Library</title>
</head>
<body class="metro " style="overflow-y: hidden;">
<header class="bg-blue" data-load="/template/header"></header>

<p><a href="/log/login" target="_self">客户登陆</a></p>
<p><a href="/log/register" target="_self">客户注册</a></p>
<p><a href="/log/adminlogin" target="_self">员工登录</a></p>
<p><a href="/log/register" target="_self">员工注册</a></p>

</body>
</html>