<form id="" name="" method="post" action="">
  <p>ID
    <input name="CustomerID" type="text" disabled="disabled" id="CustomerID" value="<?php echo $this->CustomerID;?>" />
  </p>
  <p>名字
    <input name="CustomerName" type="text" id="CustomerName" value="<?php echo $this->CustomerName;?>" />
  </p>
  <p>学校
    <input name="CustomerCollage" type="text" id="CustomerCollage" value="<?php echo $this->CustomerCollage;?>" />
  </p>
  <p>手机
    <input name="CustomerSelfMobile" type="text" id="CustomerSelfMobile" value="<?php echo $this->CustomerSelfMobile;?>" />
  </p>
  <p>地址
    <input name="CustomerSelfAddress" type="text" id="CustomerSelfAddress" value="<?php echo $this->CustomerSelfAddress;?>" />
  </p>
  <p>转运站手机
    <input name="CustomerAvatarMobile" type="text" id="CustomerAvatarMobile" value="<?php echo $this->CustomerAvatarMobile;?>" />
  </p>
  <p>转运站地址
    <input name="CustomerAvatarAddress" type="text" id="CustomerAvatarAddress" value="<?php echo $this->CustomerAvatarAddress;?>" />
  </p>
  <p>邮箱
    <input name="CustomerMail" type="text" id="CustomerMail" value="<?php echo $this->CustomerMail;?>" />
  </p>
  <p>QQ
    <input name="CustomerQQ" type="text" id="CustomerQQ" value="<?php echo $this->CustomerQQ;?>" />
  </p>
  <p>人人
    <input name="CustomerRenren" type="text" id="CustomerRenren" value="<?php echo $this->CustomerRenren;?>" />
  </p>
  <p>微信
    <input name="CustomerWeixin" type="text" id="CustomerWeixin" value="<?php echo $this->CustomerWeixin;?>" />
  </p>
  <p>支付宝
    <input name="CustomerAlipay" type="text" id="CustomerAlipay" value="<?php echo $this->CustomerAlipay;?>" />
  </p>
  <p>重置密码</p>
  <p>
    <input type="submit" name="resetPassword" id="resetPassword" value="重置密码" />
    <input type="submit" name="updateInfor" id="updateInfor" value="修改信息" />
    <input type="button" name="close" id="close" value="关闭" />
  </p>
</form>
