<form id="" name="" method="post" action="">
  <p>ID
    <input name="PackageID" type="text" disabled="disabled" id="PackageID" value="<?php echo $this->PackageID;?>" />
  </p>
  <p>收货人
    <input name="PackageOwnerID" type="text" disabled="disabled" id="PackageOwnerID" value="<?php echo $this->PackageOwnerID;?>" />
  </p>
  <p> 手机号
    <input name="PackageOwnerMobile" type="text" id="PackageOwnerMobile" value="<?php echo $this->PackageOwnerMobile;?>" />
  </p>
  <p> 快递公司
    <input name="PackageExpressCompany" type="text" id="PackageExpressCompany" value="<?php echo $this->PackageExpressCompany;?>" />
  </p>
  <p> 运单号
    <input name="PackageExpressTrackNumber" type="text" id="PackageExpressTrackNumber" value="<?php echo $this->PackageExpressTrackNumber;?>" />
  </p>
  <p> 照片
    <input name="PackageSnapshot" type="text" id="PackageSnapshot" value="<?php echo $this->PackageSnapshot;?>" />
  </p>
  <p> 重量
    <input name="PackageWeight" type="text" id="PackageWeight" value="<?php echo $this->PackageWeight;?>" />
  </p>
  <p> 运费
    <input name="PackageFare" type="text" id="PackageFare" value="<?php echo $this->PackageFare;?>" />
  </p>
  <p> 入库时间
    <input name="PackageInTime" type="text" disabled="disabled" id="PackageInTime" value="<?php echo $this->PackageInTime;?>" />
  </p>
  <p> 出库时间
    <input name="PackageOutTime" type="text" disabled="disabled" id="PackageOutTime" value="<?php echo $this->PackageOutTime;?>" />
  </p>
  <p> 包裹状态
    <input name="PackageStatus" type="text" disabled="disabled" id="PackageStatus" value="<?php echo $this->PackageStatus;?>" />
  </p>
  <p>
    <input type="button" name="close" id="close" value="关闭" />
  </p>
</form>
