<!doctype html>
<html class="ks-webkit537 ks-webkit ks-chrome36 ks-chrome">
<head>
<meta charset="utf-8">
<title>收货地址 | 淘宝网</title>
<link type="text/css" rel="stylesheet" href="http://g.tbcdn.cn//tb/mbis/0.2.3/deliver/css/deliver.css" rev="stylesheet">
</head>
<body>
<div class="page" id="J_Page">
  <div class="form-box" id="J_FormBox">
    <div class="global-msg msg-b hide" id="J_MsgGlobal"> <i></i>
      <div class="msg-tit msg-vm"></div>
      <div class="msg-cnt"></div>
    </div>
    <div class="item item-title"> <span class="item-label" id="J_DeliverTitle">修改收货地址　</span>电话号码、手机号选填一项,其余均为必填项 </div>
    <form id="J_FormDeliver" action="" method="post">
      <div class="item item-devision" id="J_ItemDivision"> <span class="item-label">所在地区：<i>*</i></span>
        <select name="prov" id="J_Province" data-key="province" data-available="true" style="">
          <option value="110000">北京</option>
          <option value="120000">天津</option>
          <option value="130000">河北省</option>
          <option value="140000">山西省</option>
          <option value="150000">内蒙古自治区</option>
          <option value="210000">辽宁省</option>
          <option value="220000">吉林省</option>
          <option value="230000">黑龙江省</option>
          <option value="310000">上海</option>
          <option value="320000">江苏省</option>
          <option value="330000">浙江省</option>
          <option value="340000">安徽省</option>
          <option value="350000">福建省</option>
          <option value="360000">江西省</option>
          <option value="370000">山东省</option>
          <option value="410000">河南省</option>
          <option value="420000">湖北省</option>
          <option value="430000">湖南省</option>
          <option value="440000" <?php echo ($this->CustomerAvatarAddress["StationProvince"]=='广东' ? 'selected' : '')?>>广东省</option>
          <option value="450000">广西壮族自治区</option>
          <option value="460000">海南省</option>
          <option value="500000">重庆</option>
          <option value="510000">四川省</option>
          <option value="520000">贵州省</option>
          <option value="530000">云南省</option>
          <option value="540000">西藏自治区</option>
          <option value="610000">陕西省</option>
          <option value="620000">甘肃省</option>
          <option value="630000">青海省</option>
          <option value="640000">宁夏回族自治区</option>
          <option value="650000">新疆维吾尔自治区</option>
          <option value="710000">台湾</option>
          <option value="810000">香港特别行政区</option>
          <option value="820000">澳门特别行政区</option>
          <option value="990000">海外</option>
        </select>
        <select name="country" id="J_Country" data-key="country" data-available="" style="display: none;">
        </select>
        <select name="provExt" id="J_ProvinceExt" data-key="provinceExt" data-available="" style="display: none;">
        </select>
        <select name="city" id="J_City" data-key="city" data-available="true" style="">
          <option value="440100">广州市</option>
          <option value="440200">韶关市</option>
          <option value="440300" <?php echo ($this->CustomerAvatarAddress["StationCity"]=='深圳市' ? 'selected' : '')?>>深圳市</option>
          <option value="440400">珠海市</option>
          <option value="440500">汕头市</option>
          <option value="440600">佛山市</option>
          <option value="440700">江门市</option>
          <option value="440800">湛江市</option>
          <option value="440900">茂名市</option>
          <option value="441200">肇庆市</option>
          <option value="441300">惠州市</option>
          <option value="441400">梅州市</option>
          <option value="441500">汕尾市</option>
          <option value="441600">河源市</option>
          <option value="441700">阳江市</option>
          <option value="441800">清远市</option>
          <option value="441900">东莞市</option>
          <option value="442000">中山市</option>
          <option value="442101">东沙群岛</option>
          <option value="445100">潮州市</option>
          <option value="445200">揭阳市</option>
          <option value="445300">云浮市</option>
        </select>
        <select name="area" id="J_Area" data-key="area" data-available="true" style="">
          <option value="440303">罗湖区</option>
          <option value="440304">福田区</option>
          <option value="440305">南山区</option>
          <option value="440306">宝安区</option>
          <option value="440307" <?php echo ($this->CustomerAvatarAddress["StationDistrict"]=='龙岗区' ? 'selected' : '')?>>龙岗区</option>
          <option value="440308">盐田区</option>
          <option value="440320">光明新区</option>
          <option value="440321">坪山新区</option>
          <option value="440322">大鹏新区</option>
          <option value="440323">龙华新区</option>
        </select>
        <select name="town" id="J_Town" data-key="town" data-available="true" style="">
          <option value="440307003">平湖街道</option>
          <option value="440307006">坪地街道</option>
          <option value="440307007">坪山街道</option>
          <option value="440307008">坑梓街道</option>
          <option value="440307009">葵涌街道</option>
          <option value="440307010">大鹏街道</option>
          <option value="440307011">南澳街道</option>
          <option value="440307012">南湾街道</option>
          <option value="440307013">坂田街道</option>
          <option value="440307014">布吉街道</option>
          <option value="440307015">龙城街道</option>
          <option value="440307016">龙岗街道</option>
          <option value="440307017" <?php echo ($this->CustomerAvatarAddress["StationStreets"]=='横岗街道' ? 'selected' : '')?>>横岗街道</option>
          <option value="440307401">深圳市大工业区</option>
          <option value="">我不知道...</option>
        </select>
        <div class="tip-town" id="J_TipTown"> <i></i>建议选择街道/乡镇信息,让配送服务更精准！ </div>
        <div class="msg-box">
          <div class="msg msg-error hide" id="J_MsgDivision"> <i></i>
            <div class="msg-cnt"></div>
          </div>
        </div>
      </div>
      <div class="item item-postcode" id="J_ItemPostCode"> <span class="item-label">邮政编码：<i>*</i></span>
        <input name="post" data-item="postcode" data-pattern="^[\da-zA-Z]{3,10}$" data-msg="请输入邮编" class="i-text" id="J_PostCode" type="text" value="<?php echo $this->CustomerAvatarAddress["StationZipCode"];?>">
        <div class="msg hide" id="J_MsgPostCode"> <i></i>
          <div class="msg-cnt">邮编不存在</div>
        </div>
      </div>
      <div class="item item-street" id="J_ItemStreet"> <span class="item-label">街道地址：<i>*</i></span>
        <div class="ks-combobox" id="J_ComboboxStreet">
          <div class="ks-combobox-input-wrap">
            <textarea class="ks-combobox-input i-ta" aria-combobox="list" role="combobox" autocomplete="off" name="addressDetail" id="J_Street" placeholder="不需要重复填写省市区，必须大于5个字符，小于120个字符" data-pattern="^.{5,120}$" data-msg="5-120个字符，一个汉字为两个字符" data-ph="不需要重复填写省市区，必须大于5个字符，小于120个字符"><?php echo $this->CustomerAvatarAddress["StationApartment"]."_".$this->CustomerSelfMobile;?></textarea>
          </div>
        </div>
        <div class="msg-box">
          <div class="msg msg-error hide" id="J_MsgStreet"> <i></i>
            <div class="msg-cnt"></div>
          </div>
        </div>
      </div>
      <div class="item item-name" id="J_ItemName"> <span class="item-label">收货人姓名：<i>*</i></span>
        <input name="fullName" class="i-text" type="text" id="J_Name" placeholder="长度不超过25个字" data-pattern="^.{2,25}$" data-msg="2-25个字符，一个汉字为两个字符" data-ph="长度不超过25个字" value="<?php echo $this->CustomerName;?>">
        <div class="msg hide" id="J_MsgName"> <i></i>
          <div class="msg-cnt"></div>
        </div>
      </div>
      <div class="item item-mobile" id="J_ItemMobile"> <span class="item-label">手机号码：</span>
        <input name="mobile" class="i-text" type="text" id="J_Mobile" placeholder="电话号码、手机号码必须填一项" data-pattern="^\d{6,20}$" data-ph="电话号码、手机号码必须填一项6-20个数字" data-msg="6-20个数字" value="<?php echo $this->CustomerAvatarMobile;?>">
        <div class="msg hide" id="J_MsgMobile"> <i></i>
          <div class="msg-cnt"></div>
        </div>
      </div>
      <div class="item item-phone" id="J_ItemPhone"> <span class="item-label">电话号码：</span>
        <input name="phoneSection" class="i-text i-text-short" id="J_PhoneSection" placeholder="区号" data-ph="区号" type="text" value="">
        -
        <input name="phoneCode" class="i-text i-text-short" id="J_PhoneCode" placeholder="电话号码" data-ph="电话号码" type="text" value="">
        -
        <input name="phoneExt" id="J_PhoneExt" class="i-text i-text-short" placeholder="分机" data-ph="分机" type="text" value="">
        <input type="hidden" value="" id="J_Phone" data-pattern="^\d+-\d+(?:-\d+)?$" data-msg="格式错误">
        <div class="msg hide" id="J_MsgPhone"> <i></i>
          <div class="msg-cnt"></div>
        </div>
      </div>
      <div class="item item-set-default" id="j_ItemSetDefault"> <span class="item-label">设为默认地址：</span>
        <input type="checkbox" class="i-chk" name="defaultAddress" id="J_SetDefault">
        <label for="J_SetDefault">设置为默认收货地址</label>
      </div>
    </form>
  </div>
</div>
<img src="http://gm.mmstat.com/member.6.2" width="1" height="1">
</body>
</html>