<?php if ($this->CapCreditTable): ?>

<table width="1280" border="1">
  <tr>
    <th scope="col">时间</th>
    <th scope="col">流水</th>
    <th scope="col">说明</th>
  </tr>
  <?php foreach ($this->CapCreditTable as $Value): ?>
  <tr>
    <td><?php echo $this->escape($Value["CapCreditTimeStamp"]) ?></td>
    <td><?php echo $this->escape($Value["CapCreditLedger"]) ?></td>
    <td><?php echo $this->escape($Value["CapCreditDetail"]) ?></td>
  </tr>
  <?php endforeach; ?>
</table>
<?php endif; ?>
