<form id="findlostpackageform" name="findlostpackageform" method="post" action="findlostpackageform">
  <p>货物来源
    <input type="text" name="Channel" id="Channel" />
  </p>
  <p> 快递公司
    <input type="text" name="ExpressCompany" id="ExpressCompany" />
  </p>
  <p> 运单号
    <input type="text" name="PackageExpressTrackNumber" id="PackageExpressTrackNumber" />
  </p>
   <p> 送达时间
    <input type="text" name="ArriveTime" id="ArriveTime" />
  </p>
   <p> 货物价值
    <input type="text" name="PackageValue" id="PackageValue" />
  </p>
  <p>
    <input type="submit" name="register" id="register" value="登记" />
  </p>
</form>