<!DOCTYPE html>
<html>
                <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
                <meta name="product" content="Metro UI CSS Framework">
                <meta name="description" content="Simple responsive css framework">
                <meta name="author" content="Sergey S. Pimenov, Ukraine, Kiev">
                <!-- Load CSS Libraries -->
                <link href="<?php echo $this->baseUrl('/css/metro-bootstrap.css');?>" rel="stylesheet">
                <link href="<?php echo $this->baseUrl('/css/metro-bootstrap-responsive.css');?>" rel="stylesheet">
                <link href="<?php echo $this->baseUrl('/css/iconFont.css');?>" rel="stylesheet">
                <link href="<?php echo $this->baseUrl('/css/docs.css');?>" rel="stylesheet">
                <link href="<?php echo $this->baseUrl('/js/prettify/prettify.css');?>" rel="stylesheet">

                <!-- Load JavaScript Libraries -->
                <script src="<?php echo $this->baseUrl('/js/jquery/jquery.min.js');?>"></script>
                <script src="<?php echo $this->baseUrl('/js/jquery/jquery.widget.min.js');?>"></script>
                <script src="<?php echo $this->baseUrl('/js/jquery/jquery.mousewheel.js');?>"></script>
                <script src="<?php echo $this->baseUrl('/js/prettify/prettify.js');?>"></script>

                <!-- Metro UI CSS JavaScript plugins -->
                <script src="<?php echo $this->baseUrl('/js/metro.min.js');?>"></script>
                <!-- Local JavaScript -->
                <script src="<?php echo $this->baseUrl('/js/docs.js');?>"></script>
                <script>
				/**
 * Created by Seven on 2014/8/18.
 */

function createWindowTaobao(){
    $.Dialog({
        overlay: false,
        shadow: true,
        flat: false,
        icon: '<img src="images/excel2013icon.png">',
        title: 'Window 8.1 Everywhere For Everything!',
        content: '',
        onShow: function(_dialog){
            var html = [
                '<iframe width="700" height="500" src="/template/taobao" frameborder="0" allowfullscreen></iframe>'
            ].join("");
            $.Dialog.content(html);
        }
    });
}
function createWindowJD(){
    $.Dialog({
        overlay: false,
        shadow: true,
        flat: false,
        icon: '<img src="images/excel2013icon.png">',
        title: 'Window 8.1 Everywhere For Everything!',
        content: '',
        onShow: function(_dialog){
            var html = [
                '<iframe width="700" height="500" src="/template/jingdong" frameborder="0" allowfullscreen></iframe>'
            ].join("");
            $.Dialog.content(html);
        }
    });
}
function createWindowAmazon(){
    $.Dialog({
        overlay: false,
        shadow: true,
        flat: false,
        icon: '<img src="images/excel2013icon.png">',
        title: 'Window 8.1 Everywhere For Everything!',
        content: '',
        onShow: function(_dialog){
            var html = [
                '<iframe width="700" height="500" src="/template/amazon" frameborder="0" allowfullscreen></iframe>'
            ].join("");
            $.Dialog.content(html);
        }
    });
}
function createWindowDangdang(){
    $.Dialog({
        overlay: false,
        shadow: true,
        flat: false,
        icon: '<img src="images/excel2013icon.png">',
        title: 'Window 8.1 Everywhere For Everything!',
        content: '',
        onShow: function(_dialog){
            var html = [
                '<iframe width="700" height="500" src="/template/dangdang" frameborder="0" allowfullscreen></iframe>'
            ].join("");
            $.Dialog.content(html);
        }
    });
}
function createWindowVIP(){
    $.Dialog({
        overlay: false,
        shadow: true,
        flat: false,
        icon: '<img src="images/excel2013icon.png">',
        title: 'Window 8.1 Everywhere For Everything!',
        content: '',
        onShow: function(_dialog){
            var html = [
                '<iframe width="700" height="500" src="/template/vip" frameborder="0" allowfullscreen></iframe>'
            ].join("");
            $.Dialog.content(html);
        }
    });
}
function createWindowYHD(){
    $.Dialog({
        overlay: false,
        shadow: true,
        flat: false,
        icon: '<img src="images/excel2013icon.png">',
        title: 'Window 8.1 Everywhere For Everything!',
        content: '',
        onShow: function(_dialog){
            var html = [
                '<iframe width="700" height="500" src="/template/yhd" frameborder="0" allowfullscreen></iframe>'
            ].join("");
            $.Dialog.content(html);
        }
    });
}	
                </script>
                <title>Metro UI CSS : Metro Bootstrap CSS Library</title>
                </head>
                <body class="metro">
<header class="bg-dark" data-load="/template/header"></header>
<div class="container">
                  <h1> <a href="/workspace"><i class="icon-arrow-left-3 fg-darker smaller"></i></a> </h1>
                  <div class="grid">
    <h3>仓库名片</h3>
    <div class="row">
                      <div class="span9">
        <p class="description">请使用页面中的收件人信息填写快递单。注意收件人姓名与本人保持一致。并将本人<code>手机号码</code>填写在地址栏的最后。 </p>
        <h4>收件人信息</h4>
        <dl class="horizontal">
                          <dt><strong>收件人</strong></dt>
                          <dd><?php echo $this->CustomerName;?></dd>
                          <dt><strong>联系电话</strong></dt>
                          <dd><?php echo $this->CustomerAvatarMobile;?></dd>
                          <dt><strong>地址</strong></dt>
                          <dd><?php echo $this->CustomerAvatarAddress["StationProvince"]."省 ".$this->CustomerAvatarAddress["StationCity"]." ".$this->CustomerAvatarAddress["StationDistrict"]." ".$this->CustomerAvatarAddress["StationStreets"];?></dd>
                          <dd><?php echo $this->CustomerAvatarAddress["StationApartment"]."_".$this->CustomerSelfMobile;?></dd>
                          <dt><strong>邮编</strong></dt>
                          <dd><?php echo $this->CustomerAvatarAddress["StationZipCode"];?></dd>
                        </dl>
      </div>
                    </div>
    <div class="tile-group seven"> <a class="tile double bg-red" href="javascript:void(0)" onclick="createWindowTaobao()">
      <div class="tile-content image"> <img src=""> </div>
      <div class="brand"> <span class="label fg-white">淘宝/天猫</span> </div>
      </a> <a class="tile bg-orange" href="javascript:void(0)" onclick="createWindowJD()">
      <div class="tile-content image"> <img src=""> </div>
      <div class="brand"> <span class="label fg-white">京东</span> </div>
      </a> <a class="tile bg-orange" href="javascript:void(0)" onclick="createWindowAmazon()">
      <div class="tile-content image"> <img src=""> </div>
      <div class="brand"> <span class="label fg-white">亚马逊</span> </div>
      </a> <a class="tile bg-orange" href="javascript:void(0)" onclick="createWindowDangdang()">
      <div class="tile-content image"> <img src=""> </div>
      <div class="brand"> <span class="label fg-white">当当</span> </div>
      </a> <a class="tile bg-dark" href="javascript:void(0)">
      <div class="tile-content image"> <img src=""> </div>
      <div class="brand"> <span class="label fg-white">唯品会</span> </div>
      </a> <a class="tile bg-dark" href="javascript:void(0)">
      <div class="tile-content image"> <img src=""> </div>
      <div class="brand"> <span class="label fg-white">1号店</span> </div>
      </a> </div>
  </div>
                </div>
<script src="js/hitua.js"></script>
</body>
</html>