<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>
</head>

<body>
<form action="mystorehouseform" method="post" target="_new" id="mystorehouseform">
  等待打包的货物
  <?php if ($this->PackageWaitingList): ?>
  <table width="1280" border="1">
    <tr>
      <th scope="col">&nbsp;</th>
      <th scope="col">编号</th>
      <th scope="col">收货人</th>
      <th scope="col">手机号</th>
      <th scope="col">快递公司</th>
      <th scope="col">运单号</th>
      <th scope="col">照片</th>
      <th scope="col">重量</th>
      <th scope="col">运费</th>
      <th scope="col">入库时间</th>
      <th scope="col">出库时间</th>
      <th scope="col">状态</th>
    </tr>
    <?php foreach ($this->PackageWaitingList as $Value): ?>
    <tr>
      <th scope="row"><input type="radio" name="PackageIDR" id="PackageIDR" value="<?php echo $Value["PackageID"] ?>" /></th>
      <td><?php echo $Value["PackageID"] ?></td>
      <td><?php echo $Value["PackageOwnerID"] ?></td>
      <td><?php echo $Value["PackageOwnerMobile"] ?></td>
      <td><?php echo $Value["PackageExpressCompany"] ?></td>
      <td><?php echo $Value["PackageExpressTrackNumber"] ?></td>
      <td><?php echo $Value["PackageSnapshot"] ?></td>
      <td><?php echo $Value["PackageWeight"] ?></td>
      <td><?php echo $Value["PackageFare"] ?></td>
      <td><?php echo $Value["PackageInTime"] ?></td>
      <td><?php echo $Value["PackageOutTime"] ?></td>
      <td><?php echo $Value["PackageStatus"] ?></td>
    </tr>
    <?php endforeach; ?>
  </table>
  <?php else: ?>
  <p>There are no books to display.</p>
  <?php endif; ?>
  <hr />
  等待签收的货物
  <?php if ($this->PackageUnsignedList): ?>
  <table width="1280" border="1">
    <tr>
      <th scope="col">&nbsp;</th>
      <th scope="col">编号</th>
      <th scope="col">收货人</th>
      <th scope="col">手机号</th>
      <th scope="col">快递公司</th>
      <th scope="col">运单号</th>
      <th scope="col">照片</th>
      <th scope="col">重量</th>
      <th scope="col">运费</th>
      <th scope="col">入库时间</th>
      <th scope="col">出库时间</th>
      <th scope="col">状态</th>
    </tr>
    <?php foreach ($this->PackageUnsignedList as $Value): ?>
    <tr>
      <th scope="row"><input type="radio" name="PackageIDR" id="PackageIDR" value="<?php echo $Value["PackageID"] ?>" /></th>
      <td><?php echo $Value["PackageID"] ?></td>
      <td><?php echo $Value["PackageOwnerID"] ?></td>
      <td><?php echo $Value["PackageOwnerMobile"] ?></td>
      <td><?php echo $Value["PackageExpressCompany"] ?></td>
      <td><?php echo $Value["PackageExpressTrackNumber"] ?></td>
      <td><?php echo $Value["PackageSnapshot"] ?></td>
      <td><?php echo $Value["PackageWeight"] ?></td>
      <td><?php echo $Value["PackageFare"] ?></td>
      <td><?php echo $Value["PackageInTime"] ?></td>
      <td><?php echo $Value["PackageOutTime"] ?></td>
      <td><?php echo $Value["PackageStatus"] ?></td>
    </tr>
    <?php endforeach; ?>
  </table>
  <?php else: ?>
  <p>There are no books to display.</p>
  <?php endif; ?>
  <hr />
  顺利签收的货物
  <?php if ($this->PackageSignedList): ?>
  <table width="1280" border="1">
    <tr>
      <th scope="col">&nbsp;</th>
      <th scope="col">编号</th>
      <th scope="col">收货人</th>
      <th scope="col">手机号</th>
      <th scope="col">快递公司</th>
      <th scope="col">运单号</th>
      <th scope="col">照片</th>
      <th scope="col">重量</th>
      <th scope="col">运费</th>
      <th scope="col">入库时间</th>
      <th scope="col">出库时间</th>
      <th scope="col">状态</th>
    </tr>
    <?php foreach ($this->PackageSignedList as $Value): ?>
    <tr>
      <th scope="row"><input type="radio" name="PackageIDR" id="PackageIDR" value="<?php echo $Value["PackageID"] ?>" /></th>
      <td><?php echo $Value["PackageID"] ?></td>
      <td><?php echo $Value["PackageOwnerID"] ?></td>
      <td><?php echo $Value["PackageOwnerMobile"] ?></td>
      <td><?php echo $Value["PackageExpressCompany"] ?></td>
      <td><?php echo $Value["PackageExpressTrackNumber"] ?></td>
      <td><?php echo $Value["PackageSnapshot"] ?></td>
      <td><?php echo $Value["PackageWeight"] ?></td>
      <td><?php echo $Value["PackageFare"] ?></td>
      <td><?php echo $Value["PackageInTime"] ?></td>
      <td><?php echo $Value["PackageOutTime"] ?></td>
      <td><?php echo $Value["PackageStatus"] ?></td>
    </tr>
    <?php endforeach; ?>
  </table>
  <?php else: ?>
  <p>There are no books to display.</p>
  <?php endif; ?>
  <hr />
  等待核对的货物
  <?php if ($this->PackageUnfindList): ?>
  <table width="1280" border="1">
    <tr>
      <th scope="col">&nbsp;</th>
      <th scope="col">编号</th>
      <th scope="col">收货人</th>
      <th scope="col">手机号</th>
      <th scope="col">快递公司</th>
      <th scope="col">运单号</th>
      <th scope="col">照片</th>
      <th scope="col">重量</th>
      <th scope="col">运费</th>
      <th scope="col">入库时间</th>
      <th scope="col">出库时间</th>
      <th scope="col">状态</th>
    </tr>
    <?php foreach ($this->PackageUnfindList as $Value): ?>
    <tr>
      <th scope="row"><input type="radio" name="PackageIDR" id="PackageIDR" value="<?php echo $Value["PackageID"] ?>" /></th>
      <td><?php echo $Value["PackageID"] ?></td>
      <td><?php echo $Value["PackageOwnerID"] ?></td>
      <td><?php echo $Value["PackageOwnerMobile"] ?></td>
      <td><?php echo $Value["PackageExpressCompany"] ?></td>
      <td><?php echo $Value["PackageExpressTrackNumber"] ?></td>
      <td><?php echo $Value["PackageSnapshot"] ?></td>
      <td><?php echo $Value["PackageWeight"] ?></td>
      <td><?php echo $Value["PackageFare"] ?></td>
      <td><?php echo $Value["PackageInTime"] ?></td>
      <td><?php echo $Value["PackageOutTime"] ?></td>
      <td><?php echo $Value["PackageStatus"] ?></td>
    </tr>
    <?php endforeach; ?>
  </table>
  <?php else: ?>
  <p>There are no books to display.</p>
  <?php endif; ?>
  <input name="detail" type="submit" value="详情" id="detail" />
</form>
</body>
</html>
