<p>入库</p>
<p><a href="admin/registerpackage">录入包裹</a>，<a href="admin/matchpackage">匹配</a></p>
<p><a href="admin/rematchpackage">检查未匹配包裹</a></p>
<p>出库</p>
<p><a href="admin/checkouttransit">运单拣货出库</a></p>
<p><a href="admin/signtransitbill">运单签收</a></p>
<p>查询</p>
<p><a href="admin/customerlist">客户列表</a></p>
<p><a href="admin/packagelist">包裹列表</a></p>
<p><a href="admin/transitbilllist">运单列表</a></p>
<p><a href="admin/search">查找包裹/运单</a></p>
<p>&nbsp;</p>
<p><a href="admin/logout">登出</a></p>

<?php
